function GenerateProfile() {
	//variables
	var item;
	var gem;
	var enchant;
	
	// set part of profile
	var profile = "#Profile generated by Simcreator\n\n";
	profile += "demonhunter=\"Demonsand\"\n";
	profile += "level=60\n";
	profile += "race=\"night_elf\"\n";
	profile += "role=tank";
	profile += "talents=1333322\n";
	profile += "spec=vengeance\n\n";
	profile += "covenant=night_fae\n";
	profile += "soulbind=niya:1,322721/153:8:1/342270/134:8:1/320668/130:8:1/131:9:1/320659/281:8:1/352502/135:8:1/352503\n";
	profile += "renown=80\n\n";
	
	// dynamic part of profile
	profile += "#Gear\n"
	
	//head
	gem = document.getElementById("Head_Gem").value;
	profile += "head=,id=" + document.getElementById("Head").value;
	if(gem != -1) {
		profile += ",gem_id=" + gem;
	}
	profile += ",ilevel=252\n";
	
	//neck
	item = document.getElementById("Neck").value;
	profile += "neck=,id=" + item;
	if(item != 186379) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//shoulder
	gem = document.getElementById("Shoulder_Gem").value;
	item = document.getElementById("Shoulder").value;
	profile += "shoulder=,id=" + item;
	if(gem != -1) {
		profile += ",gem_id=" + gem;
	}
	if(item != 186336) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//back
	enchant = document.getElementById("Back_Enchant").value;
	profile += "back=,id=" + document.getElementById("Back").value;
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	profile += ",ilevel=252\n";
	
	//chest
	gem = document.getElementById("Chest_Gem").value;
	item = document.getElementById("Chest").value;
	enchant = document.getElementById("Chest_Enchant").value;
	profile += "chest=,id=" + item;
	if(gem != -1) {
		profile += ",gem_id=" + gem;
	}
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	if(item != 186334) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//wrist
	enchant = document.getElementById("Wrist_Enchant").value;
	profile += "wrist=,id=" + document.getElementById("Wrist").value;
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	profile += ",ilevel=252\n";
	
	//hands
	gem = document.getElementById("Hands_Gem").value;
	enchant = document.getElementById("Hands_Enchant").value;
	profile += "hands=,id=" + document.getElementById("Hands").value;
	if(gem != -1) {
		profile += ",gem_id=" + gem;
	}
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	profile += ",ilevel=252\n";
	
	//waist
	item = document.getElementById("Waist").value;
	profile += "waist=,id=" + item;
	if(item != 186332) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//legs
	profile += "legs=,id=" + document.getElementById("Legs").value;
	profile += ",ilevel=252\n";
	
	//feet
	gem = document.getElementById("Feet_Gem").value;
	enchant = document.getElementById("Feet_Enchant").value;
	profile += "feet=,id=" + document.getElementById("Feet").value;
	if(gem != -1) {
		profile += ",gem_id=" + gem;
	}
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	profile += ",ilevel=252\n";
	
	//finger 1
	item = document.getElementById("Finger1").value;
	enchant = document.getElementById("Finger1_Enchant").value;
	profile += "finger1=,id=" + item;
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	if(item != 186377) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//finger 2
	item = document.getElementById("Finger2").value;
	enchant = document.getElementById("Finger2_Enchant").value;
	profile += "finger2=,id=" + item;
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	if(item != 186377) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//trinket 1
	item = document.getElementById("Trinket1").value;
	profile += "trinket1=,id=" + item;
	if(item != 186437) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//trinket 2
	item = document.getElementById("Trinket2").value;
	profile += "trinket2=,id=" + item;
	if(item != 186437) {
		profile += ",ilevel=252\n";
	} else {
		profile += ",ilevel=259\n";
	}
	
	//mainhand
	item = document.getElementById("MH").value;
	enchant = document.getElementById("MH_Enchant").value;
	profile += "main_hand=,id=" + item;
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	profile += ",ilevel=252\n";

	
	//offhand
	item = document.getElementById("OH").value;
	enchant = document.getElementById("OH_Enchant").value;
	profile += "off_hand=,id=" + item;
	if(enchant != -1) {
		profile += ",enchant_id=" + enchant;
	}
	profile += ",ilevel=252\n";

	var e = document.getElementById("simcProfile");
	e.innerHTML = profile;
}
